<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{{ $report->title }}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 12px;
      line-height: 1.4;
      color: #333;
      margin: 0;
      padding: 20px;
    }

    .header {
      text-align: center;
      border-bottom: 2px solid #007bff;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }

    .header h1 {
      color: #007bff;
      margin: 0 0 10px 0;
      font-size: 24px;
    }

    .header .subtitle {
      color: #6c757d;
      font-size: 14px;
    }

    .summary {
      background-color: #f8f9fa;
      padding: 15px;
      border-radius: 5px;
      margin-bottom: 25px;
    }

    .summary h2 {
      margin: 0 0 15px 0;
      color: #007bff;
      font-size: 16px;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }

    .stat-box {
      text-align: center;
      padding: 10px;
      background-color: white;
      border: 1px solid #dee2e6;
      border-radius: 5px;
    }

    .stat-number {
      font-size: 20px;
      font-weight: bold;
      color: #007bff;
      display: block;
    }

    .stat-label {
      font-size: 10px;
      color: #6c757d;
      text-transform: uppercase;
      margin-top: 5px;
    }

    .project-section {
      margin-bottom: 25px;
      page-break-inside: avoid;
    }

    .project-header {
      background-color: #e9ecef;
      padding: 10px 15px;
      border-left: 4px solid #007bff;
      margin-bottom: 15px;
    }

    .project-title {
      font-size: 14px;
      font-weight: bold;
      margin: 0 0 5px 0;
      color: #007bff;
    }

    .project-meta {
      font-size: 11px;
      color: #6c757d;
    }

    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 1px solid #dee2e6;
      text-align: center;
      font-size: 10px;
      color: #6c757d;
    }
  </style>
</head>
<body>
<div class="header">
  <h1>{{ $report->title }}</h1>
  <div class="subtitle">
    {{ $report->start_date->format('F j, Y') }} - {{ $report->end_date->format('F j, Y') }}
  </div>
  <div class="subtitle">
    Generated by {{ $generator->name ?? 'System' }} on {{ $generated_at->format('F j, Y g:i A') }}
  </div>
</div>

<div class="summary">
  <h2>Report Summary</h2>
  <div class="stats-grid">
    <div class="stat-box">
      <span class="stat-number">{{ $summary['total_projects'] }}</span>
      <div class="stat-label">Projects</div>
    </div>
    <div class="stat-box">
      <span class="stat-number">{{ $summary['total_tasks'] }}</span>
      <div class="stat-label">Total Tasks</div>
    </div>
    <div class="stat-box">
      <span class="stat-number">{{ $summary['completed_tasks'] }}</span>
      <div class="stat-label">Completed</div>
    </div>
    <div class="stat-box">
      <span class="stat-number">{{ number_format($summary['total_hours'], 1) }}h</span>
      <div class="stat-label">Hours Logged</div>
    </div>
  </div>

  @if($summary['completion_rate'] > 0)
    <p><strong>Completion Rate:</strong> {{ $summary['completion_rate'] }}%</p>
  @endif
</div>

@foreach($reportItems as $item)
  <div class="project-section">
    <div class="project-header">
      <div class="project-title">{{ $item->project_name }}</div>
      <div class="project-meta">
        @if($item->contact_name)
          <strong>Contact:</strong> {{ $item->contact_name }}
        @endif
        @if($item->firm_name)
          | <strong>Firm:</strong> {{ $item->firm_name }}
        @endif
        | <strong>Hours:</strong> {{ number_format($item->total_hours, 1) }}h
        | <strong>Tasks:</strong> {{ $item->completed_task_count }}/{{ $item->task_count }} completed
      </div>
    </div>

    @if($item->notes)
      <p><strong>Notes:</strong> {{ $item->notes }}</p>
    @endif
  </div>
@endforeach

@if(empty($reportItems) || $reportItems->count() === 0)
  <div style="text-align: center; padding: 40px; color: #6c757d;">
    <p>No activity recorded for this period.</p>
  </div>
@endif

<div class="footer">
  <p>This report was generated by the Nerd Reports system.</p>
  <p>Report ID: {{ $report->uuid }} | Generated: {{ $generated_at->format('Y-m-d H:i:s') }}</p>
</div>
</body>
</html>
