<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ $subject }}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      background-color: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 20px;
    }

    .content {
      background-color: #ffffff;
      padding: 20px;
      border: 1px solid #e9ecef;
      border-radius: 8px;
    }

    .footer {
      margin-top: 20px;
      padding: 15px;
      background-color: #f8f9fa;
      border-radius: 8px;
      font-size: 14px;
      color: #6c757d;
    }

    .stats {
      display: flex;
      justify-content: space-between;
      margin: 20px 0;
      padding: 15px;
      background-color: #f8f9fa;
      border-radius: 8px;
    }

    .stat-item {
      text-align: center;
    }

    .stat-number {
      font-size: 24px;
      font-weight: bold;
      color: #007bff;
    }

    .stat-label {
      font-size: 12px;
      color: #6c757d;
      text-transform: uppercase;
    }

    .attachment-note {
      background-color: #e7f3ff;
      border-left: 4px solid #007bff;
      padding: 10px 15px;
      margin: 15px 0;
    }
  </style>
</head>
<body>
<div class="header">
  <h1>{{ $report->title }}</h1>
  <p><strong>Period:</strong> {{ $report->start_date->format('M j, Y') }} - {{ $report->end_date->format('M j, Y') }}
  </p>
  <p><strong>Generated:</strong> {{ $report->generated_at->format('M j, Y g:i A') }}</p>
</div>

<div class="content">
  {!! nl2br(e($body)) !!}

  @if(isset($variables))
    <div class="stats">
      <div class="stat-item">
        <div class="stat-number">{{ $variables['total_projects'] }}</div>
        <div class="stat-label">Projects</div>
      </div>
      <div class="stat-item">
        <div class="stat-number">{{ $variables['total_tasks'] }}</div>
        <div class="stat-label">Total Tasks</div>
      </div>
      <div class="stat-item">
        <div class="stat-number">{{ $variables['completed_tasks'] }}</div>
        <div class="stat-label">Completed</div>
      </div>
      <div class="stat-item">
        <div class="stat-number">{{ $variables['total_hours'] }}</div>
        <div class="stat-label">Hours Logged</div>
      </div>
    </div>
  @endif

  <div class="attachment-note">
    <strong>📎 Attachment:</strong> A detailed PDF report is attached to this email with complete task breakdowns and
    project summaries.
  </div>
</div>

<div class="footer">
  <p>This is an automated report generated by the Nerd Reports system.</p>
  <p>If you have any questions about this report, please contact the sender directly.</p>
</div>
</body>
</html>
